### ISSUE TITLE
Slide at the wrong place in joins

### ISSUE THREAD

**Issue by MathildeMousset** [appliedepi/slides#24]
What is currently the slide 5 is a bit weird: we have not shown them any schematics or false data, so explaining all these joins concisely without some illustration is hard. I think it is better to begin with some exemple (either maybe several of the animations, or the two toy datasets, so that at least we can say "there are many ways to combine these datasets by matching this column, here is a list).
Maybe even has the list as a recap before going on with tips/stuffs to be carefull?

**Comment by jarvisc1** [comment]
Close as old issue, reopen is needed.
