### ISSUE TITLE
sats slides review

### ISSUE THREAD

**Issue by aspina7** [appliedepi/slides#6]
@arranhamlet just chucking comments in here rather than email - doing this in a rush so sorry if sounds curt, not meant to be! 
Feel free to disregard anything and everything 

**course_intro deck**
- [x] slide 10: not enough time in a "week", we only running a two day course 
- [x] slide 11: multivariable 
- [x] slide 12: multivariable 
- [x] slide 18: between an outcome and an exposure? (technically both are variables - semantics, not fussed, imaginge some ppl would be though)
- [x] slide 19: the assumption that people have already done the intro course and know about {gtsummary}? 
- [x] slide 20: maybe put this before slide 19? 
- [x] slide 22: surprising {gtsummary} default to show median with a ttest... but see that you go in to details in following slides

**basic_regression deck** 
- [x] slide 2: outcome vs variable - whatever you decide for slide 18 in intro deck do same here 
- [x] slide 3: controlling for confounding and effect modification 
- [x] slide 6/7: maybe add comments to the code? 
- [x] slide 8: here you use dependent and independent variables (pick one and stick to it - maybe even a slide on terminology early on, maybe in intro?, to say they are the same, e.g. outcome = dependent, exposure/explanatory = independent, then stick to saying dependent and independent) 
- [x] slide 9: again maybe show comments on code
- [x] slide 9: consider using bullet points for text (heavy) 
- [x] slide 9: "There is only one value and so the regression analysis will not show anything." - not sure I get this, are you trying to say that the output will not show gender? 
- [x] slide 10: association instead of relationship? 
- [ ] slide 10: add mantel-haenszel estimates? 
- [x] slide 11: maybe dont say simple, can put people off if they havent been following :) 

**multivariable regression deck** 
- [x] slide 2: univariate (univariable would be a single variable, technically univariate is a bivariable or multivariable, but with a single outcome)- i know super anal im sorry 
- [x] slide 3: univariate 
- [x] slide 3: maybe bullet points rather than full sentences? 
- [x] slide 4: independent and outcome :)  
- [x] slide 6: maybe a slide on effect modification? 
- [x] slide 7: you may need to explain why it is relevant to train and test - traditionally epis would just say this is the data that I have available in this outbreak and as such I would not be interested in using the same regression on a different set of data. The point is that you are able to show how reliable your regression is, rather than necessarily predicting other scenarios. 
- [x] slide 10: typo: a theory noT the other way round
- [x] slide 10: expert knowledge in epi speak is biological plausibility 
- [x] slide 10: reject important variables when there is confounding .... and effect modification 
- [x] slide 11: worth a note on principle of parsimony (occam's razor)? 
- [x] slide 14: point 2, in caretwe needs a space
- [x] slide 16: do you not need to use unique() or distinct()? - repeated var names
- [x] slide 18: important to note, variables should be included based on valid reasoning, e.g. biological plausibility, or a previously well established association 
- [x] slide 19: univariable 
- [x] slide 20: code comments, and maybe an explanation of the point? 
- [x] slide 21: univariable 
- [x] slide 21: maybe add in counts too - as discussed [here ](https://community.appliedepi.org/t/adding-columns-for-count-percent-of-controls-and-cases-to-tbl-uvregression-output/474)
- [x] slide 30: link to community? (also for the other slide decks) 

**final_exercise deck** 
- [x] slide 4: maybe just add a screenshot of the output doc?

Thanks a bunch arran it all looks really great!

**Comment by arranhamlet** [comment]
This is awesome, thank you very much for going through these! As you can see I'm still adjusting to using variable not variate 😅.

I'll aim to get these done before the pilot.

**Comment by arranhamlet** [comment]
Do you have a preferred way of adding in mantel-haenszel estimates? 

I've found the thread you commented on that links to https://github.com/R4EPI/epitabulate/blob/master/R/gt_wrappers.R, but the function does not appear to work with the current set up. 

Any advice?

**Comment by aspina7** [comment]
hey hey - so using the gt_mh_odds function should work (see the link to example code in the test scripts below). 

https://github.com/R4EPI/epitabulate/blob/master/tests/testthat/test-gt_wrappers.R#L795

An alternative could be to use the old epitabulate::tab_univariate function in the meantime .... but thats not gtsummary and will eventually be depricated. Try the above first and if doesnt work then let me know.... 
https://github.com/R4EPI/epitabulate/blob/master/R/tab_univariate.R

In an absolute bin fire situation we can always go back to the base version ..... 
https://stat.ethz.ch/R-manual/R-devel/library/stats/html/mantelhaen.test.html

**Comment by aspina7** [comment]
side note just noticed in the exercises you have said univariable :)

**Comment by jarvisc1** [comment]
Closing old issue
